export {
  caniuse,
  defaultBackgroundColor,
  formatSolutionTimestamp,
  formatTeamMemberName,
  getAcceptedStatusDetails,
  getMarkerPresentation,
  getProblemHeaderBackgroundImage,
  getSolutionModalTitle,
  getSolutionResultMeta,
  resolveSrkAssetUrl,
  shouldShowTimeColumn,
  srkSupportedVersions,
  type MarkerPresentation,
  type SolutionResultMeta,
} from '@algoux/standard-ranklist-renderer-component-core';
